language: python

sudo: false
matrix:
  include:
    - env: TOXENV=codestyle

    - python: 2.6
      env: TOXENV=py26
      dist: trusty
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      sudo: true
      dist: xenial
    - python: pypy
      env: TOXENV=pypy

install: travis_retry pip install tox
script: tox

notifications:
  email: false
